name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Modules
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Test-ModuleManifest
        shell: pwsh
        run: |
          Test-ModuleManifest -Path ./src/PS.MsGraph/PS.MsGraph.psd1

      - name: Invoke-ScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src/ -Settings ./PSScriptAnalyzerSettings.psd1 -Recurse -EnableExit

      - name: Test publish to PowerShell Gallery
        shell: pwsh
        env:
          PSGalleryApiKey: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          Publish-Module -Path './src/PS.MsGraph' -Repository PSGallery -NuGetApiKey $env:PSGalleryApiKey -WhatIf -Verbose
